name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  build:
    runs-on: build
    steps:
      - uses: actions/checkout@v4

      - name: Build the documentation
        run: |
          docker run --rm  -v "${PWD}:/docs" squidfunk/mkdocs-material build -d build/site
          ls -al
          
