name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  build:
    runs-on: build
    steps:
      - uses: actions/checkout@v4

      - name: Build the documentation
        run: |
          docker run --rm -u "$(id -u):$(id -g)" -v "${PWD}:/docs" squidfunk/mkdocs-material build -d build/site
          ls -al
      - name: Create the container
        run: |
          docker image rm my-documentation || true
          docker build -f Dockerfile.nginx -t my-documentation .
          docker image ls --all
      - name: Run the container
        run: |
          docker container stop mydoc || true
          docker container rm mydoc || true
          docker run --name mydoc -d --restart always -p 8081:80 my-documentation
      - name: Test the container
        run: |
          docker run --name integrationtest --network host --rm -v "${PWD}/integrationtest.sh:/integrationtest.sh:ro" alpine/curl bash /integrationtest.sh
      - name: Clean the container in any case
        if: always()
        run: |
          docker container stop integrationtest || true
          docker container rm integrationtest || true
          docker container stop mydoc || true
          docker container rm mydoc || true
