name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  build:
    runs-on: build
    steps:
      - name: Set file and folder permissions to local user
        run: |
          echo "Setting file and folder permissions in case something with user and group root was created in a previous run."
          echo "Using user and group $(id -u):$(id -g) for the whole folder."
          docker run --rm -v "${PWD}":/project bash:latest chown --recursive $(id -u):$(id -g) /project
      - uses: actions/checkout@v4
      - name: Build the documentation
        run: |
          # Build the static html page into the folder "build/site"
          # The parameter "-u" is required because otherwise the generated site would have root:root as user:group.
          docker run --rm -u "$(id -u):$(id -g)" -v "${PWD}:/docs" squidfunk/mkdocs-material build -d build/site
          # List the contents of the project folder
          ls -al
      - name: Create the container
        run: |
          # Just to be safe: Remove eventually existing images.
          docker image rm my-documentation || true

          # Build the documentation image
          docker build -f Dockerfile.nginx -t my-documentation .
          docker image ls --all
      - name: Run the documentation container
        run: |
          # Just to be safe: Stop and remove eventually existing containers.
          docker container stop mydoc || true
          docker container rm mydoc || true

          # Run the documentation image on the build agent.
          docker run --name mydoc -d --restart always -p 8081:80 my-documentation
      - name: Test the container
        run: |
          # Run the integration test from the file "integrationtest.sh" against the running documentation image.
          docker run --name docintegrationtest --network host --rm -v "${PWD}/integrationtest.sh:/integrationtest.sh:ro" ellerbrock/alpine-bash-curl-ssl bash /integrationtest.sh
      - name: Clean the container in any case
        if: always()
        run: |
          docker container stop docintegrationtest || true
          docker container rm docintegrationtest || true
          docker container stop mydoc || true
          docker container rm mydoc || true
